import localFont from "next/font/local";
import { Londrina_Solid } from 'next/font/google'
import "./globals.css";


import { Metadata } from 'next'
import Header from "../components/Header"
import { headers } from 'next/headers'
import { cookieToInitialState } from "wagmi";

import {config} from '../lib/config'
import Web3ModalProvider from '../lib/wagmi-provider'


const londrina = Londrina_Solid({
  subsets: ['latin'],
  weight: ['100', '300', '400', '900'],
  variable: '--font-londrina',
  display: 'swap',
})


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <html lang="en" className={londrina.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-pbr-yellow`}
      >
        <Web3ModalProvider initialState={initialState}>
          <Header />
          {children}
          </Web3ModalProvider>
      
      </body>
    </html>
  );
}
